src/Entity/Ressource.php
<?php

namespace App\Entity;

use App\Repository\RessourceRepository;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

#[ORM\Entity(repositoryClass: RessourceRepository::class)]
/**
 * @ORM\Entity
 * @Vich\Uploadable
 */

class Ressource
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    /**
     * @Vich\UploadableField(mapping="ressource_images", fileNameProperty="url_image")
     */
    private $imageFile;

    #[ORM\Column(length: 255)]
    private ?string $url_image = null;

    #[ORM\Column(length: 255)]
    private ?string $url = null;

    #[ORM\ManyToOne(inversedBy: 'ressources')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getUrlImage(): ?string
    {
        return $this->url_image;
    }

    public function setUrlImage(string $url_image): self
    {
        $this->url_image = $url_image;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;
    }
}

src/Entity/Social.php
<?php

namespace App\Entity;

use App\Repository\SocialRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\Security;

#[ORM\Entity(repositoryClass: SocialRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Social
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $social_url = null;

    #[ORM\ManyToOne(inversedBy: 'socials')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(length: 255)]
    private ?string $font_awesome_icon_name = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSocialUrl(): ?string
    {
        return $this->social_url;
    }

    public function setSocialUrl(string $social_url): self
    {
        $this->social_url = $social_url;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function setCreatedUser(Security $userSecurity): self
    {
        $this->user = $userSecurity->getUser();
        return $this;
    }

    public function getFontAwesomeIconName(): ?string
    {
        return $this->font_awesome_icon_name;
    }

    public function setFontAwesomeIconName(string $font_awesome_icon_name): self
    {
        $this->font_awesome_icon_name = $font_awesome_icon_name;

        return $this;
    }
}

src/Entity/Template.php
<?php

namespace App\Entity;

use App\Repository\TemplateRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TemplateRepository::class)]
class Template
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $baseline = 'baseline lorem';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $youtube_url = '47Kk_uQq2jg';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_1_bg_color = '#FCFAF8';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_1_title_color = '#383838';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_1_baseline_color = '#383838';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section2_bg_color = '#FCFAF8';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_3_bg_color = '#FCFAF8';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_3_bg_color_card = '#FFFFFF';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_3_color_txt_card = '#FCFAF8';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_4_bg_color = '#FCFAF8';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_4_bg_color_btn = '#FFFFFF';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_4_color_txt_btn = '#FFFFFF';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_5_bg_color = '#FCFAF8';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_5_icon_color = '#383838';

    #[ORM\OneToOne(inversedBy: 'template', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;





    public function getId(): ?int
    {
        return $this->id;
    }




    public function getBaseline(): ?string
    {
        return $this->baseline;
    }

    public function setBaseline(string $baseline): self
    {
        $this->baseline = $baseline;

        return $this;
    }

    public function getYoutubeUrl(): ?string
    {
        return $this->youtube_url;
    }

    public function setYoutubeUrl(string $youtube_url): self
    {
        $this->youtube_url = $youtube_url;

        return $this;
    }

    public function getSection1BgColor(): ?string
    {
        return $this->section_1_bg_color;
    }

    public function setSection1BgColor(?string $section_1_bg_color): self
    {
        $this->section_1_bg_color = $section_1_bg_color;

        return $this;
    }

    public function getSection1TitleColor(): ?string
    {
        return $this->section_1_title_color;
    }

    public function setSection1TitleColor(?string $section_1_title_color): self
    {
        $this->section_1_title_color = $section_1_title_color;

        return $this;
    }

    public function getSection1BaselineColor(): ?string
    {
        return $this->section_1_baseline_color;
    }

    public function setSection1BaselineColor(?string $section_1_baseline_color): self
    {
        $this->section_1_baseline_color = $section_1_baseline_color;

        return $this;
    }

    public function getSection2BgColor(): ?string
    {
        return $this->section2_bg_color;
    }

    public function setSection2BgColor(?string $section2_bg_color): self
    {
        $this->section2_bg_color = $section2_bg_color;

        return $this;
    }

    public function getSection3BgColor(): ?string
    {
        return $this->section_3_bg_color;
    }

    public function setSection3BgColor(?string $section_3_bg_color): self
    {
        $this->section_3_bg_color = $section_3_bg_color;

        return $this;
    }

    public function getSection3BgColorCard(): ?string
    {
        return $this->section_3_bg_color_card;
    }

    public function setSection3BgColorCard(?string $section_3_bg_color_card): self
    {
        $this->section_3_bg_color_card = $section_3_bg_color_card;

        return $this;
    }

    public function getSection3ColorTxtCard(): ?string
    {
        return $this->section_3_color_txt_card;
    }

    public function setSection3ColorTxtCard(?string $section_3_color_txt_card): self
    {
        $this->section_3_color_txt_card = $section_3_color_txt_card;

        return $this;
    }



    public function getSection4BgColor(): ?string
    {
        return $this->section_4_bg_color;
    }

    public function setSection4BgColor(?string $section_4_bg_color): self
    {
        $this->section_4_bg_color = $section_4_bg_color;

        return $this;
    }

    public function getSection4BgColorBtn(): ?string
    {
        return $this->section_4_bg_color_btn;
    }

    public function setSection4BgColorBtn(?string $section_4_bg_color_btn): self
    {
        $this->section_4_bg_color_btn = $section_4_bg_color_btn;

        return $this;
    }

    public function getSection4ColorTxtBtn(): ?string
    {
        return $this->section_4_color_txt_btn;
    }

    public function setSection4ColorTxtBtn(?string $section_4_color_txt_btn): self
    {
        $this->section_4_color_txt_btn = $section_4_color_txt_btn;

        return $this;
    }

    public function getSection5BgColor(): ?string
    {
        return $this->section_5_bg_color;
    }

    public function setSection5BgColor(?string $section_5_bg_color): self
    {
        $this->section_5_bg_color = $section_5_bg_color;

        return $this;
    }

    public function getSection5IconColor(): ?string
    {
        return $this->section_5_icon_color;
    }

    public function setSection5IconColor(?string $section_5_icon_color): self
    {
        $this->section_5_icon_color = $section_5_icon_color;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\HttpFoundation\File\File;


#[ORM\Entity(repositoryClass: UserRepository::class)]
/**
 * @ORM\Entity
 * @Vich\Uploadable
 */

#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    /**
     * @Vich\UploadableField(mapping="ressource_images", fileNameProperty="profile_image")
     */
    private $imageFile;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profile_image = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Ressource::class, orphanRemoval: true)]
    private Collection $ressources;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Social::class, orphanRemoval: true)]
    private Collection $socials;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Promotion::class, orphanRemoval: true)]
    private Collection $promotions;

    #[ORM\OneToOne(mappedBy: 'user', cascade: ['persist', 'remove'])]
    private ?Template $template = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;



    public function __construct()
    {
        $this->ressources = new ArrayCollection();
        $this->socials = new ArrayCollection();
        $this->promotions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getProfileImage(): ?string
    {
        return $this->profile_image;
    }

    public function setProfileImage(string $profile_image): self
    {
        $this->profile_image = $profile_image;

        return $this;
    }

    /**
     * @return Collection<int, Ressource>
     */
    public function getRessources(): Collection
    {
        return $this->ressources;
    }

    public function addRessource(Ressource $ressource): self
    {
        if (!$this->ressources->contains($ressource)) {
            $this->ressources->add($ressource);
            $ressource->setUser($this);
        }

        return $this;
    }

    public function removeRessource(Ressource $ressource): self
    {
        if ($this->ressources->removeElement($ressource)) {
            // set the owning side to null (unless already changed)
            if ($ressource->getUser() === $this) {
                $ressource->setUser(null);
            }
        }

        return $this;
    }


    /**
     * @return Collection<int, Social>
     */
    public function getSocials(): Collection
    {
        return $this->socials;
    }

    public function addSocial(Social $social): self
    {
        if (!$this->socials->contains($social)) {
            $this->socials->add($social);
            $social->setUser($this);
        }

        return $this;
    }

    public function removeSocial(Social $social): self
    {
        if ($this->socials->removeElement($social)) {
            // set the owning side to null (unless already changed)
            if ($social->getUser() === $this) {
                $social->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Promotion>
     */
    public function getPromotions(): Collection
    {
        return $this->promotions;
    }

    public function addPromotion(Promotion $promotion): self
    {
        if (!$this->promotions->contains($promotion)) {
            $this->promotions->add($promotion);
            $promotion->setUser($this);
        }

        return $this;
    }

    public function removePromotion(Promotion $promotion): self
    {
        if ($this->promotions->removeElement($promotion)) {
            // set the owning side to null (unless already changed)
            if ($promotion->getUser() === $this) {
                $promotion->setUser(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->firstname . ' ' . $this->lastname . ' ' . $this->email . ' ' . $this->profile_image;
    }

    public function getTemplate(): ?Template
    {
        return $this->template;
    }

    public function setTemplate(Template $template): self
    {
        // set the owning side of the relation if necessary
        if ($template->getUser() !== $this) {
            $template->setUser($this);
        }

        $this->template = $template;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
    public function getImageFile()
    {
        return $this->imageFile;
    }
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;
    }
}

templates/landing_page/index.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Landing Page - All dev long{% endblock %}</title>
        <script src="https://kit.fontawesome.com/c5e216e624.js" crossorigin="anonymous"></script>
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
            {{ encore_entry_script_tags('script') }}
        {% endblock %}
    </head>
    <body class="LP_body">

        <main class="LP_mainContent">
            <section 
                class="LP_infoInflu" 
                style='background:{{user.template.section1BgColor}};'
            >
                <div class="design_scroll">
                    <p>scroll</p>
                    <div class="bar"></div>
                </div>
                <div>
                    <h1 
                        class="name" 
                        style='color:{{user.template.section1TitleColor}};'
                    >
                        {{user.firstname}} {{user.lastname}}
                    </h1>
                    <p 
                        class="description" 
                        style='color:{{user.template.section1BaselineColor}};'
                    >
                        {{user.template.baseline}} 
                    </p>
                </div>
                <div class="images_container flex-column d-flex justify-content-center align-items-center">
                    <img 
                        class="image_ellipse" 
                        src="{{ asset('images/ellipse_grid.png') }}" 
                        alt=""
                    >
                    <img 
                        class="photo_influ" 
                        src="{{ asset('uploads/ressources/')}}{{user.profileImage }}" 
                        alt=""
                    >
                </div>
                <div 
                    class="icone_container d-flex justify-content-center align-items-center"
                >
                    {% for social in user.socials %}
                        <a 
                            style='color:{{user.template.section5IconColor}};' 
                            href="{{social.socialUrl }}"
                        >
                            <i class="{{social.fontAwesomeIconName }}"></i>
                        </a>
                    {% endfor %}
                </div>
            </section>
            {% if user.template.youtubeUrl|length > 0 %}
                <section 
                    class="LP_section_video" 
                    style='background:{{user.template.section2BgColor}};'
                 >
                    <h2 
                        class="title"
                    >
                        Vidéo 
                        <span class="lp_text_mark">
                            Youtube
                        </span>
                    </h2>

                 
                    <div style="width:100%;max-width:800px;margin:0 auto;">
                       <div id="ytplayer"></div>
                        <script>
                            // Load the IFrame Player API code asynchronously.
                            var tag = document.createElement('script');
                            tag.src = "https://www.youtube.com/player_api";
                            var firstScriptTag = document.getElementsByTagName('script')[0];
                            firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

                            // Replace the 'ytplayer' element with an <iframe> and
                            // YouTube player after the API code downloads.
                            var player;
                            function onYouTubePlayerAPIReady() {
                                player = new YT.Player('ytplayer', {
                                height: '500px',
                                width: '100%',
                                videoId: '{{user.template.youtubeUrl }}'
                                });
                            }
                        </script>
                    </div>
                    
                </section>
            {% endif %}
            {% if user.promotions|length > 0  %}
                <section 
                    class="LP_section_code_promo" 
                    style='background:{{user.template.section3BgColor}};' >
                    <h2 class="title_section">
                        Codes promos <br> 
                        <span class="lp_text_mark">
                            du Jour
                        </span>
                    </h2>

                    <p class="description">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. 
                        Debitis, velit illo! Unde sequi consectetur vitae asperiores cumque vel veniam 
                        amet ea neque aperiam consequuntur, saepe et alias dolor sed impedit?
                    </p>
                    <div class="container_all_code d-flex justify-content-center align-items-center">
                    {% for promotion in user.promotions %}

                        <div 
                            class="container_one_code" 
                            style='background:{{user.template.section3BgColorCard}}' 
                        >
                            <span 
                                class="lp_text_mark code_promo"
                                style='color:{{promotion.colorTxt}}; background:{{promotion.bgColor}}'
                            
                            >
                                {{promotion.promotionalCode }}
                            </span> 
                                — {{promotion.dateStart|date("d/m/Y") }} 
                                - {{promotion.dateEnd|date("d/m/Y") }}
                            <p>{{ promotion.name }}</p>
                        </div>
                
                    {% endfor %}
                    </div>
                </section>
            {% endif %}
        {% if user.ressources|length > 0 %}
            <section 
                class="LP_rester_informer" 
                style='background:{{user.template.section4BgColor}};'
            >
                <h2 class="title_section">
                    <span class="lp_text_mark">Rester</span> 
                    informer
                </h2>
                <p class="description">Les liens à ne pas manquer</p>
                <div class="event_and_formContact">
                    <div class="container_all_event">
                        {% for ressource in user.ressources %}
                        <div class="ressource_container">
                            <a href="{{ressource.url}}">
                                <div 
                                    class="container_oneEvent boutique ressource_image" 
                                    style='background:{{user.template.section4BgColorBtn}};'
                                 >
                                    <img 
                                        src="{{ asset('uploads/ressources/')}}{{ressource.urlImage }}" 
                                        alt="{{ ressource.name }}"
                                    >
                                </div>
                                <span 
                                    class="ressource_title" 
                                    style='color:{{user.template.section4ColorTxtBtn}};'
                                >
                                    {{ ressource.name }}
                                </span>
                            </a>
                        </div>
                          {% endfor %}
                    </div>
                    <div class="formulaire_de_contact">
                        <h2>
                            Formulaire de 
                            <span class="lp_text_mark">contact</span>
                        </h2>
                        <div class="container_contact">
                        <form action="">
                            <div>
                                <input type="text" placeholder="Nom*" required>
                            </div>
                            <div>
                                <input type="text" placeholder="Prenom*" required>
                            </div>
                            <div>
                                <input type="email" placeholder="Mail*" required>
                            </div>
                            <div>
                                <input type="tel" placeholder="Téléphone*" required>
                            </div>
                            <div>
                                <input type="text" placeholder="Objet*" required>
                            </div>
                            <div>
                                <textarea name="" id="" cols="10" rows="10" placeholder="Message*"></textarea>
                            </div>
                            <button type="submit">Envoyer</button>
                        </form>
                    </div>
                </div>
            </section>
         {% endif %}
        {% if user.socials|length > 0 %}
            
                <section 
                    class="LP_rsx_sociaux" 
                    style='background:{{user.template.section5BgColor}};'>
                    <h2 class="section_title">Résaux</h2>
                    <p class="description">
                        Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                    </p>
                    <div class="icone_container d-flex justify-content-center align-items-center">
                        {% for social in user.socials %}
                            <a 
                                style='color:{{user.template.section5IconColor}};'
                                href="{{social.socialUrl }}"
                            >
                                <i class="{{social.fontAwesomeIconName }}"></i>
                            </a>
                        {% endfor %}
                    </div>
                </section>
          
        {% endif  %}
        </main>
    </body>
</html>