src/Entity/Promotion.php
<?php

namespace App\Entity;

use App\Repository\PromotionRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PromotionRepository::class)]
class Promotion
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $promotional_code = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_start = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_end = null;

    #[ORM\ManyToOne(inversedBy: 'promotions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $bg_color = '#14CF93';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $color_txt = '#09d393';



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPromotionalCode(): ?string
    {
        return $this->promotional_code;
    }

    public function setPromotionalCode(string $promotional_code): self
    {
        $this->promotional_code = $promotional_code;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }


    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getBgColor(): ?string
    {
        return $this->bg_color;
    }

    public function setBgColor(?string $bg_color): self
    {
        $this->bg_color = $bg_color;

        return $this;
    }

    public function getColorTxt(): ?string
    {
        return $this->color_txt;
    }

    public function setColorTxt(?string $color_txt): self
    {
        $this->color_txt = $color_txt;

        return $this;
    }
}

src/Entity/Ressource.php
<?php

namespace App\Entity;

use App\Repository\RessourceRepository;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

#[ORM\Entity(repositoryClass: RessourceRepository::class)]
/**
 * @ORM\Entity
 * @Vich\Uploadable
 */

class Ressource
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    /**
     * @Vich\UploadableField(mapping="ressource_images", fileNameProperty="url_image")
     */
    private $imageFile;

    #[ORM\Column(length: 255)]
    private ?string $url_image = null;

    #[ORM\Column(length: 255)]
    private ?string $url = null;

    #[ORM\ManyToOne(inversedBy: 'ressources')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getUrlImage(): ?string
    {
        return $this->url_image;
    }

    public function setUrlImage(string $url_image): self
    {
        $this->url_image = $url_image;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;
    }
}

src/Entity/Social.php
<?php

namespace App\Entity;

use App\Repository\SocialRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\Security;

#[ORM\Entity(repositoryClass: SocialRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Social
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $social_url = null;

    #[ORM\ManyToOne(inversedBy: 'socials')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(length: 255)]
    private ?string $font_awesome_icon_name = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSocialUrl(): ?string
    {
        return $this->social_url;
    }

    public function setSocialUrl(string $social_url): self
    {
        $this->social_url = $social_url;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function setCreatedUser(Security $userSecurity): self
    {
        $this->user = $userSecurity->getUser();
        return $this;
    }

    public function getFontAwesomeIconName(): ?string
    {
        return $this->font_awesome_icon_name;
    }

    public function setFontAwesomeIconName(string $font_awesome_icon_name): self
    {
        $this->font_awesome_icon_name = $font_awesome_icon_name;

        return $this;
    }
}

src/Entity/Template.php
<?php

namespace App\Entity;

use App\Repository\TemplateRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TemplateRepository::class)]
class Template
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $baseline = 'baseline lorem';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $youtube_url = '47Kk_uQq2jg';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_1_bg_color = '#FCFAF8';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_1_title_color = '#383838';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_1_baseline_color = '#383838';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section2_bg_color = '#FCFAF8';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_3_bg_color = '#FCFAF8';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_3_bg_color_card = '#FFFFFF';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_3_color_txt_card = '#FCFAF8';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_4_bg_color = '#FCFAF8';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_4_bg_color_btn = '#FFFFFF';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_4_color_txt_btn = '#FFFFFF';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_5_bg_color = '#FCFAF8';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section_5_icon_color = '#383838';

    #[ORM\OneToOne(inversedBy: 'template', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;





    public function getId(): ?int
    {
        return $this->id;
    }




    public function getBaseline(): ?string
    {
        return $this->baseline;
    }

    public function setBaseline(string $baseline): self
    {
        $this->baseline = $baseline;

        return $this;
    }

    public function getYoutubeUrl(): ?string
    {
        return $this->youtube_url;
    }

    public function setYoutubeUrl(string $youtube_url): self
    {
        $this->youtube_url = $youtube_url;

        return $this;
    }

    public function getSection1BgColor(): ?string
    {
        return $this->section_1_bg_color;
    }

    public function setSection1BgColor(?string $section_1_bg_color): self
    {
        $this->section_1_bg_color = $section_1_bg_color;

        return $this;
    }

    public function getSection1TitleColor(): ?string
    {
        return $this->section_1_title_color;
    }

    public function setSection1TitleColor(?string $section_1_title_color): self
    {
        $this->section_1_title_color = $section_1_title_color;

        return $this;
    }

    public function getSection1BaselineColor(): ?string
    {
        return $this->section_1_baseline_color;
    }

    public function setSection1BaselineColor(?string $section_1_baseline_color): self
    {
        $this->section_1_baseline_color = $section_1_baseline_color;

        return $this;
    }

    public function getSection2BgColor(): ?string
    {
        return $this->section2_bg_color;
    }

    public function setSection2BgColor(?string $section2_bg_color): self
    {
        $this->section2_bg_color = $section2_bg_color;

        return $this;
    }

    public function getSection3BgColor(): ?string
    {
        return $this->section_3_bg_color;
    }

    public function setSection3BgColor(?string $section_3_bg_color): self
    {
        $this->section_3_bg_color = $section_3_bg_color;

        return $this;
    }

    public function getSection3BgColorCard(): ?string
    {
        return $this->section_3_bg_color_card;
    }

    public function setSection3BgColorCard(?string $section_3_bg_color_card): self
    {
        $this->section_3_bg_color_card = $section_3_bg_color_card;

        return $this;
    }

    public function getSection3ColorTxtCard(): ?string
    {
        return $this->section_3_color_txt_card;
    }

    public function setSection3ColorTxtCard(?string $section_3_color_txt_card): self
    {
        $this->section_3_color_txt_card = $section_3_color_txt_card;

        return $this;
    }



    public function getSection4BgColor(): ?string
    {
        return $this->section_4_bg_color;
    }

    public function setSection4BgColor(?string $section_4_bg_color): self
    {
        $this->section_4_bg_color = $section_4_bg_color;

        return $this;
    }

    public function getSection4BgColorBtn(): ?string
    {
        return $this->section_4_bg_color_btn;
    }

    public function setSection4BgColorBtn(?string $section_4_bg_color_btn): self
    {
        $this->section_4_bg_color_btn = $section_4_bg_color_btn;

        return $this;
    }

    public function getSection4ColorTxtBtn(): ?string
    {
        return $this->section_4_color_txt_btn;
    }

    public function setSection4ColorTxtBtn(?string $section_4_color_txt_btn): self
    {
        $this->section_4_color_txt_btn = $section_4_color_txt_btn;

        return $this;
    }

    public function getSection5BgColor(): ?string
    {
        return $this->section_5_bg_color;
    }

    public function setSection5BgColor(?string $section_5_bg_color): self
    {
        $this->section_5_bg_color = $section_5_bg_color;

        return $this;
    }

    public function getSection5IconColor(): ?string
    {
        return $this->section_5_icon_color;
    }

    public function setSection5IconColor(?string $section_5_icon_color): self
    {
        $this->section_5_icon_color = $section_5_icon_color;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

templates/dashboard/index.html.twig
{% extends 'base_dashboard.html.twig' %}

{% block title %}DashBoard Client{% endblock %}

{% block body %}

<div class="dashboard_container">
    <div class="dashboard_side_bar">
        <div class="sidebar_header">
            <i  class=" fa-solid fa-gauge"></i>
            <span>DashBoard</span>
        </div>
        <div class="sidebar_content">
            <ul>
                <li>
                    <a href="#promotion_dashboard">
                        <i class="fa-solid fa-tags"></i>
                         <span>Promotions</span>
                    </a>
                </li>
                <li>
                     <a href="#ressource_dashboard">
                        <i class="fa-solid fa-arrow-up-right-from-square"></i>
                        <span>Ressources</span>
                     </a>
                </li>
                <li>
                       <a href="#social_dashboard"><i class="fa-regular fa-thumbs-up"></i>
                       <span>Réseaux</span>
                       </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="dashboard_content">
    <div class="imp_link">
         <a class="go_back" href="{{ path('app_home') }}"><i class="fa-solid fa-arrow-left"></i> Retour</a>
        <a class="go_back" href="{{ path('app_logout') }}"><i class="fa-solid fa-arrow-right-from-bracket"></i>  Déconnexion</a>
    </div>
       
        <div class="dashboard_content_row">
                <div class="row_header">
                    <h2>Template</h2>
                    <span class="line"></span>
                </div>
                <table class="table">
                    <tr class="tr">
                        <th class="thead thead1 ">Titre</th>
                        <th class="thead">Baseline</th>
                        <th class="thead">Lien all dev long</th>
                        <th class="thead">Youtube</th>
                        <th class="thead">Fond Section 1</th>
                        <th class="thead">Couleur titre section 1</th>
                    </tr>
                    {% if user.template %}
                        <tr >
                            <td class="tbody tbody1">{{user.firstname}} {{user.lastname}}</td>
                            <td class="tbody tbody1">{{ user.template.baseline ?: user.template.baseline }}</td>
                            <td class="tbody tbody1"><a target="blank" href="https://127.0.0.1:8001/landing-page/{{ user.slug}}">https://127.0.0.1:8001/landing-page/{{ user.slug}}</a></td>
                            <td class="tbody tbody1">{{ user.template.youtubeUrl}}</td>
                            <td style="background:{{ user.template.section1BgColor }};color:white;" class="tbody color_td">{{ user.template.section1BgColor}}</td>
                            <td style="background:{{ user.template.section1TitleColor }}; color:white;" class="tbody color_td">{{ user.template.section1TitleColor}}</td>
                        </tr>
                    {% endif %}
                </table>
                {% if user.template %}
                  <div class="content_row_footer">
                  <span>Pour plus de modification  cliquer ici</span>
                    <a  class="btn"  href="{{ path('app_template_edit', { 'id': user.template.id}) }}">
                        <i class="custom_icon fa-solid fa-pen-to-square"></i>
                    </a>
                  </div>
                  {% else %}
                      <div class="content_row_footer">
                        <span>Pour ajouter un template  cliquer ici</span>
                            <a  class="btn"  href="{{ path('app_new_template') }}">
                                 <i class="fa-solid fa-plus"></i>
                            </a>
                        </div>
                {% endif %}

        </div>
        <div class="dashboard_content_row">

                <div class="row_header">
                    <h2 id="promotion_dashboard">Promotions</h2>
                    <span class="line"></span>
                </div>
                <table class="table">
                    <tr class="tr">
                        <th></th>
                        <th class="thead thead1 ">Nom</th>
                        <th class="thead">Code</th>
                        <th class="thead">Début</th>
                        <th class="thead">Fin</th>
                        <th class="thead">Couleur 1</th>
                        <th class="thead">Couleur 2</th>
                    </tr>
                        {% for promotion in user.promotions %}
                        <tr>
                            <td class="tbody tbodyedit">
                                <a  class='edit_link' href="{{ path('app_promotion_edit', { 'id': promotion.id}) }}">
                                    <i class="custom_icon fa-solid fa-pen-to-square"></i>
                                </a>
                                <a class='delete_link'  href="{{ path('app_promotion_delet', { 'id': promotion.id}) }}">
                                    <i class="custom_icon fa-solid fa-trash"></i>
                                </a>
                            </td>
                            <td class="tbody tbody1">{{ promotion.name }}</td>
                            <td class="tbody">{{promotion.promotionalCode }}</td>
                            <td class="tbody">{{promotion.dateStart|date("d/m/Y") }}</td>
                            <td class="tbody">{{promotion.dateEnd|date("d/m/Y") }}</td>
                            <td style="background:{{ promotion.bgColor }};" class="tbody color_td">{{ promotion.bgColor }}</td>
                            <td  style="background:{{ promotion.colorTxt }};"  class="tbody color_td">{{ promotion.colorTxt }}</td>
                        </tr>
                        {% endfor %}

                </table>
                  <a  class="btn" href="{{ path('app_new_promo') }}">
                    <i class="fa-solid fa-plus"></i>
                  </a>
        </div>
          <div class="dashboard_content_row">
                <div class="row_header">
                    <h2 id="ressource_dashboard">Ressources</h2>
                    <span class="line"></span>
                </div>
                <table class="table">
                    <tr class="tr">
                        <th></th>
                        <th class="thead thead1 ">Nom</th>
                        <th class="thead">Lien</th>
                        <th class="thead">Image</th>

                    </tr>
                        {% for ressource in user.ressources %}
                        <tr>
                            <td class="tbody tbodyedit">
                                <a  class='edit_link' href="{{ path('app_ressource_edit', { 'id': ressource.id}) }}">
                                    <i class="custom_icon fa-solid fa-pen-to-square"></i>
                                </a>
                                <a class='delete_link'   href="{{ path('app_ressource_delet', { 'id': ressource.id}) }}">
                                    <i class="custom_icon fa-solid fa-trash"></i>
                                </a>
                            </td>
                            <td class="tbody tbody1">{{ ressource.name }}</td>
                            <td  class="tbody"><a href="{{ressource.url }}">{{ressource.url }}</a></td>
                            <td  class="tbody">
                                <div class="vich_image">
                                    <img src="{{ asset('uploads/ressources/')}}{{ressource.urlImage }}" alt="">
                                </div>
                            </td>

                        </tr>
                        {% endfor %}

                </table>
                  <a  class="btn" href="{{ path('app_new_ressource') }}">
                    <i class="fa-solid fa-plus"></i>
                  </a>
        </div>
         <div class="dashboard_content_row">
                <div class="row_header">
                    <h2 id="social_dashboard">Réseaux</h2>
                    <span class="line"></span>
                </div>
                <table class="table">
                    <tr class="tr">
                        <th></th>
                        <th class="thead thead1 ">Nom</th>
                        <th class="thead">Lien</th>
                        <th class="thead">font</th>

                    </tr>
                           {% for social in user.socials %}
                        <tr>
                            <td class="tbody tbodyedit">
                                <a  class='edit_link' href="{{ path('app_social_edit', { 'id': social.id}) }}">
                                    <i class="custom_icon fa-solid fa-pen-to-square"></i>
                                </a>
                                <a class='delete_link' href="{{ path('app_social_delet', { 'id': social.id}) }}">
                                    <i class="custom_icon fa-solid fa-trash"></i>
                                </a>
                            </td>
                            <td class="tbody tbody1">{{ social.name }}</td>
                            <td  class="tbody"><a href="{{social.socialUrl }}">{{social.socialUrl }}</a></td>
                            <td  class="tbody"><a href="{{social.socialUrl }}">
                                <i class="social_icon_td {{social.fontAwesomeIconName }}"></i>
                            </td>

                        </tr>
                        {% endfor %}

                </table>
                  <a  class="btn" href="{{ path('app_new_social') }}">
                    <i class="fa-solid fa-plus"></i>
                  </a>
        </div>
    </div>
</div>


<h2>social</h2>
<div class="social_container">
    {% for social in user.socials %}
        <div class="social">
            <div class="social_name">{{ social.name }}</div>
             <a href="{{ path('app_social_edit', { 'id': social.id}) }}">Mettre à jour la {{social.name}}</a>
        </div>
    {% endfor %}
         <a href="{{ path('app_new_social') }}">Ajouter une nouveau réseau</a>
</div>












{% endblock %}